### ISSUE TITLE
No such command: partialReplication.getMessagesOfType

### ISSUE THREAD

**Issue by mycognosist** [cryptoscope/ssb#130]
When trying to invoke `sbotcli partial`:

`level=error run-failure="source stream call failed: muxrpc: no such command: partialReplication.getMessagesOfType"`

cc: @cblgh

**Comment by cryptix** [comment]
Ah.. This is an obsolete relic and can be removed from sbotcli.

It was an initial browser-core/-demo example and a specific case of `getSubset (and (author x) (type y))`.

**Comment by mycognosist** [comment]
Thanks for clarifying! That was what I thought from reading the code (shorthand for author & type).

**Comment by cblgh** [comment]
it has been actionated upon!

**Comment by mycognosist** [comment]
🙏🏻 🖤

**Comment by cblgh** [comment]
@mycognosist ps btw in the future if you see `close #<number>` or `fix #<number>` or `fixes #<number>` in a commit message, that means that the issue will be closed when the commit is added to the main branch. not sure if gitea et al have copied this yet, but it's pretty nifty

**Comment by mycognosist** [comment]
Oh sweet, I had no idea. Thanks for letting me know; will hold-off on closing issues when I see that in the future.
