### ISSUE TITLE
Expected secret permissions differ depending on platform

### ISSUE THREAD

**Issue by cblgh** [cryptoscope/ssb#131]
Moid pointed out an issue on SSB that uncovered the different expectations we have on permission in go-ssb. Namely:
* https://github.com/cryptoscope/ssb/blob/master/keys_default.go
* https://github.com/cryptoscope/ssb/blob/master/keys_darwin.go

OSX: set the secret perms to 0400
*: set the secret perms perms to 0600

The place this turned up was when moid was trying to run netsim on an OSX box against a go-sbot. 

Some questions then:
* What should the correct set of perms be? 
* What kind of situations & problems might we trigger if we change the linux perms to the stricter permissions of the darwin platform? 

I can make the change & PR it once we have an answer :)

cc @cryptix 

edit: oh i guess we have three sets of permissions X) https://github.com/cryptoscope/ssb/blob/master/keys_windows.go

**Comment by cblgh** [comment]
@cryptix do you think changing it so that linux's secret permissions pattern is only readable will cause errors on other machines once they upgrade? e.g. i'll definitely have to update netsim's sim-shim. maybe this is a non-issue though, since there is no client atm that's driven exlusively with go-ssb?

on a similar note, i saw somewhere that you were musing about chmod-ing the secret file to the expected permissions, since this issue keeps coming up. are you still open to that?

**Comment by cryptix** [comment]
> there is no client atm that's driven exlusively with go-ssb?

to the best of my knowledge, this is correct :)

>  are you still open to that?

yes!
