### ISSUE TITLE
Epic: Only use *testing.T in the testing goroutine

### ISSUE THREAD

**Issue by keks** [cryptoscope/ssb#2]
>yea sounds good but let's make this a meta-todo for all the repos then.
>>Ahh, I see. Yeah I think we should use an chan error for that, but I see why you did it how you did. Not sure what the best way is - maybe let everything run in goroutines in the test goroutine just read the error chans that all the goroutines write to?

https://github.com/cryptoscope/ssb/pull/1#discussion_r236057836

**Comment by cryptix** [comment]
I tried to do this on the testRefactor branch but got intangled in the weird functions we return from the setup code...

**Comment by cryptix** [comment]
pretty sure I checked muxrpc for this and change the tests.

Should also check shs, luigi and margaret, though!

**Comment by cryptix** [comment]
I just found and fixed a pretty old instance of this in secretstream.

I really hope https://github.com/golang/go/issues/28135 will get some traction.

**Comment by freight-stack** [comment]
Hi @keks  @cryptix,

This issue looks old.  Is it active?

**Comment by cryptix** [comment]
Nope, not active. All instances are resolved but has to be kept in mind.
