### ISSUE TITLE
build failed due to bugs in dependencies 

### ISSUE THREAD

**Issue by rabble** [cryptoscope/ssb#25]
┬─[rabble@r-mbp:~/g/s/g/s/c/go-sbot]─[18:15:15]─[G:master=]
╰─>$ go build -v -i
go.cryptoscope.co/ssb/internal/ctxutils
go.cryptoscope.co/ssb/message
go.cryptoscope.co/ssb/internal/mutil
go.cryptoscope.co/ssb/internal/multiserver
go.cryptoscope.co/ssb/plugins/whoami
go.cryptoscope.co/ssb/plugins/publish
go.cryptoscope.co/ssb/plugins/control
go.cryptoscope.co/ssb/blobstore
go.cryptoscope.co/margaret/multilog/badger
go.cryptoscope.co/ssb/network
go.cryptoscope.co/ssb/graph
go.cryptoscope.co/ssb/private
go.cryptoscope.co/ssb/internal/transform
# go.cryptoscope.co/margaret/multilog/badger
../../../margaret/multilog/badger/qry.go:111:13: assignment mismatch: 2 variables but item.Value returns 1 values
../../../margaret/multilog/badger/qry.go:111:26: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
../../../margaret/multilog/badger/sublog.go:36:13: assignment mismatch: 2 variables but item.Value returns 1 values
../../../margaret/multilog/badger/sublog.go:36:26: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
# go.cryptoscope.co/ssb/network
../../network/new.go:212:36: undefined: secrethandshake.ErrProtocol
../../network/new.go:234:9: undefined: secrethandshake.ErrProtocol
go.cryptoscope.co/ssb/plugins/rawread
# go.cryptoscope.co/ssb/graph
../../graph/builder.go:59:7: undefined: margaret.IsErrNulled
../../graph/builder.go:150:11: assignment mismatch: 2 variables but it.Value returns 1 values
../../graph/builder.go:150:22: not enough arguments in call to it.Value
	have ()
	want (func([]byte) error)
../../graph/builder.go:238:11: assignment mismatch: 2 variables but it.Value returns 1 values
../../graph/builder.go:238:22: not enough arguments in call to it.Value
	have ()
	want (func([]byte) error)
go.cryptoscope.co/ssb/plugins/private
go.cryptoscope.co/ssb/plugins/blobs

**Comment by PragmaticCypher** [comment]
I've just run into this issue myself trying to use the 'go install' instructions on the readme (maybe my mistake).

Building however works locally, outside of the GOPATH.

```
cd $HOME
git clone https://github.com/cryptoscope/ssb 
cd ssb
go build ./cmd/go-sbot
```

**Comment by rabble** [comment]
uh, hit this again:
 ~  go get -u github.com/cryptoscope/ssb                                                                                                                                           261ms  Sun Oct 20 19:17:20 2019
go: finding github.com/cryptoscope/ssb latest
go: github.com/cryptoscope/ssb@v0.0.0-20191016194138-eb254c7b4c99: parsing go.mod: unexpected module path "go.cryptoscope.co/ssb"
go get: error loading module requirements
 !  ~  go get -u go.cryptoscope.co/ssb                                                                                                                                            813ms  Sun Oct 20 19:17:48 2019
go: finding go.cryptoscope.co/ssb latest
go: finding github.com/AndreasBriese/bbloom latest
go: finding github.com/agl/ed25519 latest
go: finding github.com/prometheus/client_golang v1.2.1
go: finding gopkg.in/urfave/cli.v2 v2.0.0-alpha.2
go: finding gopkg.in/yaml.v2 v2.2.4
go: finding gonum.org/v1/gonum v0.6.0
go: finding github.com/prometheus/client_model latest
go: finding golang.org/x/sys latest
go: finding github.com/catherinejones/testdiff latest
go: finding go.cryptoscope.co/margaret v0.0.11
go: gopkg.in/urfave/cli.v2@v2.0.0-alpha.2: go.mod has non-....v2 module path "github.com/urfave/cli/v2" at revision v2.0.0-alpha.2
go: finding gonum.org/v1/plot latest
go: finding golang.org/x/net latest
go get: error loading module requirements

**Comment by cryptix** [comment]
> github.com/cryptoscope/ssb

This is the import path isn't used anywhere, that's what the `unexpected module path`error tries to indicate. We are using [vanity imports](https://blog.bramp.net/post/2017/10/02/vanity-go-import-paths/) to be able to move off github at some point. If you fetch anything go-ssb related please make sure to use `go.cryptoscope.co/`.... 

> ...
> go: gopkg.in/urfave/cli.v2@v2.0.0-alpha.2: go.mod has non-....v2 module path "github.com/urfave/cli/v2" at revision v2.0.0-alpha.2

hm annoying but i'm not sure why you needed to `-u` all dependencies? Just checkout a commit and build the specified deps, please.
