### ISSUE TITLE
Properly handle use of Port 0

### ISSUE THREAD

**Issue by PragmaticCypher** [cryptoscope/ssb#26]
When port 0 is specified as a listening port, it requests the OS for a random eligible port.  This may be good for multi-user setups.

Port 0 is incorrectly handled because:
  - when passed as ':0", a random port is listened on, but the advertised port is the default '8008'.
  - when passed w/ a listening IP address, the service incorrectly advertises port '0', i.e. "net:192.168.0.3:0~shs:some-key="

**Comment by cryptix** [comment]
Yikes...! Just to make it clear: it’s _only_ the advertisements that need fixing, right?

The nodejs interop tests use :0 to spawn multiple peers and I used it myself sometimes in the past.

**Comment by cryptix** [comment]
I don't think this is still true? I use listening on 0 and getting the listener in a [bunch](https://github.com/cryptoscope/ssb/blob/ed4ef7067889e94f62fae12275b50774ca192bda/sbot/blobs_test.go#L56) of [test code](https://github.com/cryptoscope/ssb/blob/ed4ef7067889e94f62fae12275b50774ca192bda/sbot/blobs_test.go#L446).

Please reopen if this doesn't work for you.
