### ISSUE TITLE
Fileutil error on android

### ISSUE THREAD

**Issue by pietgeursen** [cryptoscope/ssb#30]
I'm getting this error when running the sbot on android:

```
E/Go: panic: open /proc/sys/kernel/osrelease: permission denied
E/Go: goroutine 1 [running]:
E/Go: github.com/pietgeursen/gobotexample/vendor/modernc.org/fileutil.init.0()
E/Go: 	/home/piet/Documents/projects/go/src/github.com/pietgeursen/gobotexample/vendor/modernc.org/fileutil/fileutil_linux.go:34 +0x300
```

Using code from [this commit](https://github.com/pietgeursen/gobotexample/commit/d3cde08fcf1810c686540782cdbb193f09054776)

**Comment by cryptix** [comment]
This seems a bit rough..  https://gitlab.com/cznic/fileutil/blob/master/fileutil_linux.go#L34


That file shouldn’t build on arm but arm64 is missing there. So that’s an issue in itself.

I will ask about support and/or make a PR that doesn’t panic.

**Comment by cryptix** [comment]
In the meantime, the indexes are plugable and badger can be used.

**Comment by cryptix** [comment]
filed upstream issue: https://gitlab.com/cznic/fileutil/issues/18

**Comment by cryptix** [comment]
Still need to bump go-ssb in the gobotexample gomobile project.
