### ISSUE TITLE
sbot should fetch feeds in parallel instead of one-by-one

### ISSUE THREAD

**Issue by freight-stack** [cryptoscope/ssb#31]
Fetching data for feeds is slow because peers are connected to sequentially.  To make it faster, it can be done concurrently.

**Comment by cryptix** [comment]
agreed but we need a bound on the parallelism.. I think maybe 5 or 10 feeds per connection.

also changed the issue title a little, tell me if that feels wrong.

**Comment by freight-stack** [comment]
Maybe title is better from user perspective?  It will make bugs upfront to them.  The title looks programmer facing :).

**Comment by cryptix** [comment]
Okay how about a Tag for „slowness“ / optimizations?

**Comment by freight-stack** [comment]
I am happy if user understands.  Maybe (slowness) in title?

**Comment by freight-stack** [comment]
:joy:
