### ISSUE TITLE
SSB Room

### ISSUE THREAD

**Issue by freight-stack** [cryptoscope/ssb#42]
Add support to host [SSB Rooms](https://github.com/staltz/ssb-room).

SSB room act as a proxy to for user to connect an discover each other but does not have access to user data.

**Comment by cryptix** [comment]
> but does not have access to user data

if we do that (not store all the feeds) we can't construct the trust/follow graph and thus have to accept anonymous connections.

At that point it might be easier to do this project as a standalone thing _just_ using go-muxrpc. The result of that project could also give us a better idea what _common tools_ could be split out from this repo.

**Comment by cryptix** [comment]
@staltz would you be down for a pairing session to nail down out some details and spare me reversing js code..? 😬 [the faq](https://github.com/staltz/ssb-room/blob/master/FAQ.md#how-does-this-work) is a bit under specified (what is forked from ssb-tunnel and how is it different).

**Comment by staltz** [comment]
@cryptix These UML diagrams might help you on the way: https://hackmd.io/Yx8I1n9DTSCaHx6CQk5XcA?view but it's difficult for me to get on a call because I just started two freelancing gigs this month. I think asynchronous communication (like this) will be easier.

**Comment by freight-stack** [comment]
Is one of blockers issue #42 ?

**Comment by cryptix** [comment]
This development is happening on github.com/ssb-ngi-pointer/gossb-rooms,

Since it doesn't need any of the database complexities and will introduce others (like a admin dashboard) it felt cleaner to have a new repo.
