### ISSUE TITLE
muxrpc CallError: Error - no such command: gossip.connect

### ISSUE THREAD

**Issue by cryptix** [cryptoscope/ssb#58]
```
sbotcli connect "net:scuttle.space:8008:~shs:skBzPazHliOXCWLwloGvHYki0wPLOUeJpvW10U7MOJ4="
level=error run-failure="connect: async call failed.: error reading response from request source: muxrpc: error reading from packet source: muxrpc CallError: Error - no such command: gossip.connect"
```

This can happen because of a fallback to work around a missing feature in go-muxrpc, namely _individual handler authorization_ based on the keypair of the session. That’s why there are two muxers in the `sbot` package (public and master), like with ssb-server you only get elevated access to master if you have the same keypair as the running server.

Therefore, you can't have special privileged `gossip.connect` if you have other handlers on `gossip.*` already, like `ping`. That’s why I introduced `ctrl.*` for privileged calls.

Blobs is a better example: you have `blobs.add` and `blobs.rm` but also `blobs.has` and `blobs.get`. You don't want add and rm exposed to the public usually.

To make this less obnoxious to deal with `sbotcli connect $msAddr` [tries gossip if ctrl fails](https://github.com/cryptoscope/ssb/blob/a0ede56456de2906eb635eb6bcc3a88ea9c9eca1/cmd/sbotcli/main.go#L277).

**If you want to be sure AND you know what you need** use `sbotcli call ctrl.connect $msAddr` for a Go server and `sbotcli call gossipconnect $msAddr` against a JS ssb-server.

**Comment by 0o153** [comment]
README says:

```
sbotcli connect "net:some.ho.st:8008~shs:SomeActuallyValidPubKey="
```

In some failed examples I was convinced that it should be `@SomeActuallyValidPubKey`, beginning with `@`...

We should either clarify this in the README, or better yet drop `@` and `=.*` while parsing the message.

**Comment by cryptix** [comment]
There might have been a time where that was true but it isn’t anymore. Thanks for pointing that out.

**Comment by 0o153** [comment]
@cryptix you're right, I meant `\..*`. thanks!

**Comment by cryptix** [comment]
I changed the code in sbotcli to print the error before it falls back to the 2nd muxrpc command.

https://github.com/cryptoscope/ssb/blob/f8b517c21b5d9b8fb05f923f29e59dda9a1730e5/cmd/sbotcli/main.go#L343

I hope this fixes this issue.
