### ISSUE TITLE
Unable to redeem an invite via sbotcli

### ISSUE THREAD

**Issue by irisdelaluna** [cryptoscope/ssb#60]
```
$ sbotcli call invite.use '{"feed":"scuttle.space:8008:@skBzPazHliOXCWLwloGvHYki0wPLOUeJpvW10U7MOJ4=.ed25519~7kdhRVy9+tfcZC9G6TX58U5BTMIcR0/rN3j3rArKKLI="}'
level=error run-failure="invite.use: call failed.: error reading response from request source: muxrpc: error reading from packet source: muxrpc CallError: Error - unknown method"
```

Argument format deduced from:

https://github.com/cryptoscope/ssb/blob/a70154f9edc0532f1662f581971896f1dfcc5219/plugins/legacyinvites/guest.go#L29-L31

Well, but it doesn't matter, because it doesn't see the `invite.use` method.

**Comment by cryptix** [comment]
This one is a bit convoluted. To support this in `sbotcli` we should hook up [invites.Redeem](https://github.com/cryptoscope/ssb/blob/master/invite/legacy.go#L18) function as a proper command. To use it through `sbotcli call` requires creating the keypair from the token/seed first, to make the guest connection. Only that way the client is granted access to the `invite.use` rpc endpoint.

**Comment by cryptix** [comment]
I think this was solved.
