### ISSUE TITLE
sbotcli connect warning after install

### ISSUE THREAD

**Issue by mhfowler** [cryptoscope/ssb#79]
hey @cryptix, I started trying to run the go-sbot, following the README here. 

I was able to install go-sbot and sbotcli on my laptop (running mac OS) and on the pi. 

When I run go-sbot in either place, it appears to start up, ~/.go-ssb gets populated, 

log messages:
```
level=info t=66.427057ms event="waiting for indexes to catch up"
level=info t=67.688541ms event="repo open" feeds=0 msgs=-1
level=info t=67.717838ms event=serving ID="@rQn3+8VJCO4scVkpzDxVee6cgCp8aCldvspXXAT3EXU=.ed25519" addr=:8008 version=snapshot build=
```

in another terminal, when I run 

```sbotcli connect "net:wx.larpa.net:8008~shs:DTNmX+4SjsgZ7xyDh5xxmNtFqa6pWi5Qtw7cE8aR9TQ="```
I get the warning:
```
level=warn event="connect command failed" err="muxrpc: didnt get length of next body (frames:0): EOF"
level=error run-failure="connect: async call failed.: muxrpc: didnt get length of next body (frames:0): EOF"
```

Above, I'm using the address of your pub which I found in the README. I've also tried a few other pub addresses from my gossip.json generated by patchwork. 

also tried,
```sbotcli connect "net:ssb.learningsocieties.org:8008~shs:uMiN0TRVMGVNTQUb6KCbiOi/8UQYcyojiA83rCghxGo="```

and get this warning,
```
level=warn event="connect command failed" err="muxrpc: error decoding json from request source: invalid character 'c' looking for beginning of value"
level=error run-failure="connect: async call failed.: muxrpc: didnt get length of next body (frames:0): EOF"
```

do you know the cause?  or another test I should I do?

**Comment by cryptix** [comment]
Whops... This looks familiar. Def not your fault. Sorry you had to go through that.

I need to push a patch or two and finally add some tests for `sbotcli`.

**Comment by cryptix** [comment]
@mhfowler I pushed a patch that should make connect (and publish) work again. Git pull and rebuild the cli tool should fix the issue.


As a side node: when the server is running, you want to look for these messages:

`level=debug t=45h18m59.094480107s event=update-replicate feed-want-count=10364 hops=2 took=23.901691557s`

this tells you how much feeds the server wants. It might oscillate a little.. I opened #75 to track that.

Also, go-ssb basically comes with https://github.com/ssbc/ssb-incoming-guard by default. So you need to follow pubs that you want to connect to first. similary it won't accept connections unless it or a friend of a friend in hops range follows them.

Contact messages can be places rather easily with `sbotcli publish contact --following @theFeedPubKey.ed25519`.

**Comment by mhfowler** [comment]
thanks @cryptix pulled the change and looks good!

```root@sari-sari1:/srv/go-sbot/ssb# sbotcli publish contact --following @uMiN0TRVMGVNTQUb6KCbiOi/8UQYcyojiA83rCghxGo=.ed25519
event=published type=contact ref="%7RUNgLbdvlcSyzNIpuYz6B7JnBz55sYF+yLuKjD3/TM=.sha256"
root@sari-sari1:/srv/go-sbot/ssb# sbotcli connect "net:ssb.learningsocieties.org:8008~shs:uMiN0TRVMGVNTQUb6KCbiOi/8UQYcyojiA83rCghxGo="
event="connect reply"
(string)("connected")
```

also thanks for the explanation about ssb-incoming-guard functionality and the log messages

**Comment by cryptix** [comment]
Purrfect! Closing this then.
