### ISSUE TITLE
Where to set the functional options API for sbot?

### ISSUE THREAD

**Issue by mycognosist** [cryptoscope/ssb#84]
Thanks to your [great docs](https://dev.scuttlebutt.nz/#/golang/?id=sbot) over at dev.scuttlebutt.nz, I know that it's possible to alter the functionality of the `sbot` server using the options API (for example, in order to define a custom database mountpoint). However, I'm not sure how to do this in practice.

Based on the test code in [`ssb/cmd/sbotcli/simple_test.go`](https://github.com/cryptoscope/ssb/blob/a4c84f1b423ddf0460e3bd33794c95495328846e/cmd/sbotcli/simple_test.go), my current assumption is that the options need to be defined in [`ssb/cmd/sbotcli/main.go`](https://github.com/cryptoscope/ssb/blob/a4c84f1b423ddf0460e3bd33794c95495328846e/cmd/sbotcli/main.go) prior to compilation. Is that correct? I'd be grateful for a short explanation of how to achieve this (for example, where would I inject those definitions? In `func initClient()` or elsewhere?).

Thanks in advance ☺️

**Comment by cryptix** [comment]
Hmm... Interesting! :)

Could you give a bit more context on what you are trying to do? The list of all the available options is best looked at on [this godoc page for the sbot package](https://pkg.go.dev/go.cryptoscope.co/ssb/sbot#Option).

The example you linked to is basically a slimmed down version of `cmd/go-sbot/main.go` which is basically just a thin wrapper which unpacks CLI flags and passes them on to the options API.

If go-sbot doesn't have the option you are looking for (I vaguely believe it does have all of them but would like to fix that if it doesn't) the code to create a peer inside another go program is exactly like that in the example. You just add the options (with the package name first) as one more argument to `sbot.Sbot(...)`. They are variadic, so the number doesn't matter.

HTH?

**Comment by cryptix** [comment]
ah.. btw, `sbotcli` is _just_ a `ssb-client`. The server/bot magic is in `ssb/sbot` which has an options.go, etc. but you don't need to mess with any of that unless you want new options that aren't there yet.

**Comment by mycognosist** [comment]
@cryptix 

Thanks for the extra details! I think I understand now.

My question was basically: how to select the different options? Now I see that they're exposed by `go-sbot` via flags. So I can set hops to 2, for example: `go-sbot -hops 2`. Or I could set a custom mountpoint: `go-sbot -repo "/some/other/dir"`. Cool. Thanks again.
