### ISSUE TITLE
Sbot error: broken bitmap file

### ISSUE THREAD

**Issue by mycognosist** [cryptoscope/ssb#85]
I'm breaking things over here 😆 

`go-sbot: failed to instantiate ssb server: sbot: failed compress multilog userFeeds: failed to load all sublogs: roaringfiles: broken bitmap file (key:00002d02007fdfbe8b8d86a7d3f72182e364d4a8bbcb44554222ea406b7dfdaec29a): roaringfiles: unpack of 00002d02007fdfbe8b8d86a7d3f72182e364d4a8bbcb44554222ea406b7dfdaec29a failed: error in roaringArray.readFrom: could not read initial cookie: EOF`

I believe this error occurred after I published a post with this command:

`sbotcli publish post "[@glyph](@HEqy940T6uB+T+d9Jaa58aNfRzLx9eRWqkZljBmnkmk=.ed25519) 聞こえますか?"`

```bash
sbotcli --version
alpha4 (rev: snapshot, built: )
```

```bash
go-sbot -version
t=30.312µs version=snapshot build=
```

**Comment by cryptix** [comment]
uh... i havn't seen this one before. publishing utf8 shouldn't concern the indexes at all (they just store sequence numbers).

You can wipe them and re-index by deleting the folder structer `.ssb-go/sublogs/userFeeds`.

**Comment by mycognosist** [comment]
Deleting the `tangles` and `userFeeds` (both located in `.ssb-go/sublogs/combined/`) and then reindexing seems to have done the trick.
